Update Build-Test.yml

diff --git a/.github/workflows/Build-Test.yml b/.github/workflows/Build-Test.yml
--- a/.github/workflows/Build-Test.yml
+++ b/.github/workflows/Build-Test.yml
@@ -47,13 +47,22 @@ jobs:
 
     - name: Run Unit Tests
       run: bundle exec fastlane ci_iOS
-
+    - name: Debug coverage file
+      run: |
+        echo "Listing fastlane directory:"
+        ls -la fastlane || true
+        echo "Printing coverage.lcov:"
+        if [ -f fastlane/coverage.lcov ]; then
+          cat fastlane/coverage.lcov
+        else
+          echo "coverage.lcov not found"
+        fi
     - name: Upload coverage
       uses: actions/upload-artifact@v4
       with:
         name: coverage
         path: fastlane/coverage.lcov
-        if-no-files-found: error
+        if-no-files-found: error    
   run-sonar-scan:
     runs-on: ubuntu-latest
     needs: build-and-test
